[workspace]
resolver = "2"
members = [
    "package",
    "tests",
    "bench",
]

[workspace.dependencies]
async-std = "^1.13.0"
tokio = "^1.40.0"

[workspace.dependencies.get_dir]
path = "./package"
features = ["all"]
