[package]
name = "__test__"
edition = "2024"
publish = false

[dependencies]
async-std = { workspace = true }
get_dir = { workspace = true }
tokio = { version = "^1.43.0", features = ["macros", "rt"] }
